FORMAT: 1A
HOST: http://tax-calculator.apiblueprint.org/

# shopee

tax-calculator is a simple API for store and display tax amounts.

## Order Collection [/order/{store_id}]

### List All Order Item [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "product_name": "Lucky Stretch",
                        "tax_code": 2,
                        "tax_name": "Tobacco",
                        "amount": 1000,
                        "tax_amount": 100,
                        "total_amount": 1100
                    }, {
                        "product_name": "Big Mac",
                        "tax_code": 1,
                        "tax_name": "Food",
                        "amount": 1000,
                        "tax_amount": 20,
                        "total_amount": 1020
                    }, {
                        "product_name": "Movie",
                        "tax_code": 3,
                        "tax_name": "Entertainment",
                        "amount": 150,
                        "tax_amount": 0.5,
                        "total_amount": 150.5
                    }
                ]
            }
        ]

### Create an Order [POST]

Insert total amount, total tax amount, grand total into order.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }